import './card/user-card';
import './card/pm-input-text';
import './rich-ui-shared-styles-module';
import './rich/top-menu';
import './rich/context-switcher-item';
import './rich/profile-menu';
import './rich/search-input';
import './rich/side-menu';
import './rich/active-icon';

import '@vaadin/vaadin-grid/vaadin-grid.js';
import '@vaadin/vaadin-button/vaadin-button.js';
import '@vaadin/vaadin-tabs/vaadin-tabs.js';
import '@vaadin/vaadin-dialog/vaadin-dialog.js';
import '@vaadin/vaadin-list-box/vaadin-list-box.js';
import '@vaadin/vaadin-item/vaadin-item.js';
import '@vaadin/vaadin-date-picker/vaadin-date-picker.js';
import '@vaadin/vaadin-checkbox/vaadin-checkbox.js';
import '@vaadin/vaadin-select/vaadin-select.js';